### ISSUE TITLE
bad request on searching index names

### ISSUE THREAD

**Issue by dadoeyad** [DarioBalinzo/kafka-connect-elasticsearch-source#3] opened 2019-08-05 15:21 UTC
I'm getting this following errors in taks config. The connection test works before getting to this point. 

[2019-08-05 14:59:45,929] ERROR error in searching index names (com.github.dariobalinzo.ElasticSourceConnector)
[2019-08-05 14:59:45,929] ERROR [Worker clientId=connect-1, groupId=data-dev] Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
java.lang.RuntimeException: org.elasticsearch.client.ResponseException: method [GET], host [http://elastic-dev.data:80], URI [_cat/indices], status line [HTTP/1.1 400 BAD_REQUEST]

**Comment by yongyct** [comment] 2019-09-20 08:21
is the elasticsearch port correct?

**Comment by dadoeyad** [comment] 2019-09-20 09:55
Yeah it was correct. I'm not using this anymore and I don't even remember what was it.

**Comment by DarioBalinzo** [comment] 2020-11-23 20:22
I'm closing the issue since the problem is resolved

**Closed** 2020-11-23 20:22 UTC
